"""add_is_admin_to_user

Revision ID: 833436060b5e
Revises: 706bfa191cbe
Create Date: 2026-06-29 19:22:07.331724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '833436060b5e'
down_revision = '706bfa191cbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
